website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/forms.py
# NECESSARY IMPORTS FOR FORMS
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, IntegerField, RadioField, Form
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError

# LOGIN FORM
class LoginForm(FlaskForm):
    email = StringField('Enter Email:', validators=[DataRequired('Kindly Enter Your Email!'), Email()])
    password = PasswordField('Enter Password:', validators=[DataRequired('Enter Your Password!')])
    submit = SubmitField('Log In')

# REGISTRATION FORM
class RegistrationForm(FlaskForm):
    name = StringField('Enter Your Name:', validators=[DataRequired('Enter Your Name Please!')])
    email = StringField('Enter Your Email:', validators=[DataRequired('Enter A Valid Email Please!'), Email()])
    password = PasswordField('Create A Password:', validators=[DataRequired('Enter Password Please!'),
                                                               EqualTo('pass_confirm', message='Passwords Must Match!')])
    pass_confirm = PasswordField('Confirm Password:', validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self, field):
        # Check if not None for that user email!
        '''
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')
        '''
        if field.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

# BASIC INDEX FORM
class InfoForm(FlaskForm):
    name = StringField('Enter your name to get started:', validators=[DataRequired('Kindly Enter Your Name!')])
    submit = SubmitField('Get Started')

# FIRST SYMPTOM FORM
class SymptomForm(FlaskForm):
    symptom1 = StringField('Enter Your Initial Symptom:', validators=[DataRequired('Kindly Enter Your Symptom!')])
    num_days = IntegerField('Number Of Days Experiencing This Symptom From:', validators=[DataRequired('Kindly Input!')])
    submit = SubmitField('Proceed')

# OTHER SYMPTOMS FORM
class OtherSymptomForm(Form):
    symptom = RadioField('', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired('Please Select Yes or No!')])

website/__init__.py
import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()

def create_app():
     app=Flask(__name__,template_folder='templates')
     app.config['SECRET_KEY']='projectkey'
     app.config['SQLALCHEMY_DATABASE_URI']='sqlite:////db.sqlite3'

     db.init_app(app)



     from .views import views
     from .auth import auth 

     app.register_blueprint(views, url_prefix='/')
     app.register_blueprint(auth, url_prefix='/')
    
     return app

website/auth.py
from flask import Blueprint, render_template,redirect,url_for,request,flash
import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle
from flask import session
from flask import Flask
from flask_mysqldb import MySQL,MySQLdb
import MySQLdb
import mysql.connector
from datetime import timedelta
import bcrypt
from bcrypt import checkpw
from flask_bcrypt import Bcrypt
from hashlib import md5

auth = Blueprint('auth', __name__)

bcrypt1=Bcrypt()
app=Flask(__name__)
mysql1=MySQL(app)
app.secret_key="0000"
app.config['MySQL_HOST']= 'localhost'

conn=mysql.connector.connect(host="localhost",user="root",password="",db="fit fact")

if(conn):
    print("connection succesful")
cursor=conn.cursor()


output=0

    


@auth.route('/login',methods=['POST','GET','DELETE'])
def login():
    return render_template("login.html",text="testing")

@auth.route('/logout')
def logout():
    session.clear()
    return render_template('home.html')
    return "<p> Log out </p>"

@auth.route('/sign-up',methods=['GET','POST','DELETE'])
def sign_up():
    return render_template("sign_up.html")

#def signup_post(): 
@auth.route('/adduser',methods=['GET','POST','DELETE'])

def add():
    email=request.form.get("u_email")
    username=request.form.get("username")
    password=request.form.get("u_password").encode('utf-8')
    hashpwd=bcrypt.hashpw(password,bcrypt.gensalt())

    cursor=conn.cursor()
    cursor.execute("INSERT INTO sign_up (Email,Username,Password) VALUES (%s, %s, %s)",(email,username,password,))
    conn.commit()
    session['name']= username
    session['email']= email

    flash('User created successfully!')
    return render_template('login.html')

@app.before_request
def before_request():
   g.username = None
   if 'username' in session:
       g.username = session['username']


@auth.route("/checkuser",methods=["POST",'GET'])
def check():

    if request.method=="POST":
        username=request.form['username']
        password=request.form['password1'].encode('utf-8')
        hashed=bcrypt.hashpw(password,bcrypt.gensalt())

        cur=conn.cursor(dictionary=True, buffered=True)
        cur.execute("SELECT * FROM sign_up WHERE Email =%s", [username])

        if cur is not None:
            data = cur.fetchone()
            try:
                password1 = data['Password']
            except Exception:
                error = 'Invalid Username or Password'
                flash(" ")
                return render_template('login.html', error=error)


            if bcrypt.checkpw(password1.encode('utf-8'),hashed):
                app.logger.info('Password Matched')
                session['logged_in'] = True
                session['username'] = username

                flash('You are now logged in', 'success')
                cur.close()
                return render_template('dashboard.html')
        

        else:
            error = 'Invalid Username or Password'
            return render_template('login.html', error=error)
 
        



@auth.route('/about')
def about():
    return render_template("about.html")


@auth.route('/predict')
def home():
    model = pickle.load(open('model.pkl', 'rb'))

    return render_template('stress.html')

@auth.route('/predicted',methods=['POST'])
def predict():
    model = pickle.load(open('model.pkl', 'rb'))
    int_features = [int(x) for x in request.form.values()]
    for x in request.form.keys():
        session[x] =  request.form.get(x)
    final_features = [np.array(int_features)]
    prediction = model.predict(final_features)

    output = round(prediction[0], 2)
    redirect(url_for('auth.exposition'))
    session['my_var'] = output

    return render_template('stress.html', prediction_text='Your Stress Level is {}'.format(output))

@auth.route('/results',methods=['POST'])
def results():

    data = request.get_json(force=True)
    prediction = model.predict([np.array(list(data.values()))])

    output = prediction[0]
    redirect(url_for('auth'.home))
    return jsonify(output)


@auth.route('/exposition',methods=['GET','POST'])
def exposition():
    value = session.get('my_var', None)
    Mood = session.get('Mood', None)
    Sleep = session.get('Hours of Sleep', None)
    return render_template('report.html', value=int(value), mood = int(Mood), sleep = int(Sleep))

@auth.route('/analyze', methods=['GET','POST'])
def analyze():
    return render_template('analyze.html')

website/views.py
from flask import Blueprint
from flask import render_template

views = Blueprint('views', __name__)

@views.route('/')
def home():
   return render_template('home.html')


website/templates/about.html
{% extends "base.html" %} {% block title %}About{% endblock %} 
{% block content %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.flip-card {
  background-color: transparent;
  width: 450px;
  height: 450px;
  perspective: 1000px;
}

.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.6s;
  transform-style: preserve-3d;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
}

.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
}

.flip-card-front {
  background-color: #bbb;
  color: black;
}

.flip-card-back {
  background-color: #2980b9;
  color: white;
  transform: rotateY(180deg);
}
</style>
</head>
<body>

<h1>ABOUT US</h1>
<h3>Hover over the image below to know about the people who created us!:</h3>

<div class="flip-card">
    <div class="flip-card-inner">
      <div class="flip-card-front">
        <img src="{{url_for('static', filename='kavya.JPG')}}" alt="Avatar" style="width:450px;height:450px;"/> 
      </div>
      <div class="flip-card-back">
        <h1>Kavya Parashar </h1>
      </br> 
    </br>
        <p1>Founder, The FIT FACT</p1>
      </br> 
    </br> 
        <p>The Charming Rationalist</p>
      </div>
    </div>
  </div>
  <br>
</br>
</br>
</br>
</br>
</br>



<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="{{url_for('static', filename='shyam.JPG')}}" alt="Avatar" style="width:450px;height:450px;">
    </div>
    <div class="flip-card-back">
      <h1>Shyam Sundar S</h1> 
      <p>Co-founder , The FIT FACT</p> 
      <p>A Prudent Perfectionist</p>
    </div>
  </div>
</div>

</body>
</html>
{% endblock %}

website/templates/analyze.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Fit Fact</title>
<link href="https://fonts.googleapis.com/css?family=Raleway|Open+Sans" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
	body {
		background: #eeeeee;
		font-family: 'Open Sans', sans-serif;
	}
    .form-inline {
        display: inline-block;
    }
	.navbar {
		font-size: 14px;
		background: #fff;
		padding-left: 16px;
		padding-right: 16px;
		border-bottom: 1px solid #d6d6d6;
		box-shadow: 0 0 4px rgba(0,0,0,.1);		
	}
	.navbar .navbar-brand {
		color: #555;
		padding-left: 0;
		font-size: 20px;
		padding-right: 50px;
		font-family: 'Raleway', sans-serif;
		text-transform: uppercase;
	}
	.navbar .navbar-brand b {
		font-weight: bold;
		color: #f04f01;
	}
	.navbar ul.nav li {
		font-size: 96%;
		font-weight: bold;		
		text-transform: uppercase;
	}
	.navbar ul.nav li.active a, .navbar ul.nav li.active a:hover, .navbar ul.nav li.active a:focus {
		color: #f04f01 !important;
		background: transparent !important;
	}
	.search-box {
        position: relative;
    }
	.search-box input.form-control, .search-box .btn {
		font-size: 14px;
		border-radius: 2px !important;
	}
	.search-box .input-group-btn {
		padding-left: 4px;		
	}
	.search-box input.form-control:focus {
		border-color: #f04f01;
		box-shadow: 0 0 8px rgba(240,79,1,0.2);
	}
	.search-box .btn-primary, .search-box .btn-primary:active {
		font-weight: bold;
		background: #f04f01;
		border-color: #f04f01;
		text-transform: uppercase;
		min-width: 90px;
	}
	.search-box .btn-primary:focus {
		outline: none;
		background: #eb4e01;
		box-shadow: 0 0 8px rgba(240,79,1,0.2);
	}
	.search-box .btn span {
		transform: scale(0.9);
		display: inline-block;
	}
	.navbar ul li i {
		font-size: 18px;
	}
	.navbar .dropdown-menu i {
		font-size: 16px;
		min-width: 22px;
	}
	.navbar .dropdown.open > a {
		background: none !important;
	}
	.navbar .dropdown-menu {
		border-radius: 1px;
		border-color: #e5e5e5;
		box-shadow: 0 2px 8px rgba(0,0,0,.05);
	}
	.navbar .dropdown-menu li a {
		color: #777;
		padding: 8px 20px;
		line-height: normal;
		font-size: 14px;
	}
	.navbar .dropdown-menu li a:hover, .navbar .dropdown-menu li a:active {
		color: #333;
	}
	.navbar .navbar-form {
		border: none;
	}
	@media (min-width: 992px){
		.form-inline .input-group .form-control {
			width: 225px;			
		}
	}
	@media (max-width: 992px){
		.form-inline {
			display: block;
		}
	}
</style>
</head> 
<body>
<nav class="navbar navbar-default navbar-expand-lg navbar-light">
	<div class="navbar-header">
		<a class="navbar-brand" href="#">THE <b>FIT FACT</b></a>  		
		<button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
			<span class="navbar-toggler-icon"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<!-- Collection of nav links, forms, and other content for toggling -->
	<div id="navbarCollapse" class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
			<li><a href="/" id="home">Home</a></li>  
			<li><a href="/about">About</a></li>			
			<li class="dropdown">
				<a data-toggle="dropdown" class="dropdown-toggle" href="#">Services <b class="caret"></b></a>
				<ul class="dropdown-menu">					
					<li><a href="/predict">Predict Stress</a></li>
					<li><a href="/">Analyze Fitness</a></li>
					<li><a href="/">Past data analysis</a></li>
				</ul>
			</li>
			<li><a href="/">Contact</a></li>
			<li><a href="/sign-up">Sign up</a></li>
		</ul>
		<form class="navbar-form form-inline navbar-right ml-auto">
			<div class="input-group search-box">
				<input type="text" class="form-control">
				<span class="input-group-btn">
					<button type="button" class="btn btn-primary"><span>Search</span></button>
				</span>
			</div>

		</form>		
	</div>
</nav>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

<title>The Fit Fact</title>

<!-- Additional CSS Files -->
<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="assets/css/font-awesome.css">

<link rel="stylesheet" href="assets/css/templatemo-training-studio.css">

</head>

<body>


<!-- ***** Main Banner Area Start ***** -->
			

   <video autoplay muted loop id="bg-video">
        <source src="{{url_for('static', filename='gym-video.mp4')}}"/>
    </video> 
	<div class="card">
		<div class="container" style="text-align:center">
			<h3>Analyze your fitness data at one click!</h3>
			<center>
				<p>
					Upload excel file with fitness data to analyze visually
				</p>
				<p>

				</p>
				<p>		
					<input type="file" name="excel" id="excelfile">
				</p>
				<p>
					<input type="submit" value="Upload File" name="submit">
				</p>
			</center>		
			
		</div>
	</div>
  
		
   
<STYle>
/* Style the video: 100% width and height to cover the entire window */
#bg-video {
  z-index:1;
  position: fixed;
}

.card {
  /* Add shadows to create the "card" effect */
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  position: absolute;
  z-index:2;
  background-color: rgba(250, 248, 242, 0.808);
  margin-left: 10%;
  margin-right: 40%;
  margin-top: 2%;
  margin-bottom: 60%;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
}

/* Add some content at the bottom of the video/page */
.content {
  position: fixed;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  color: #f1f1f1;
  width: 100%;
  padding: 20px;
}
#ex1{
  padding-left: 50px;
}
/* Style the button used to pause/play the video */
#myBtn {
  width: 200px;
  font-size: 18px;
  padding: 10px;
  border: none;
  background: #000;
  color: #fff;
  cursor: pointer;
}

#myBtn:hover {
  background: #ddd;
  color: black;
}

#titles{
  padding: 50px;
  z-index:1;
}
</STYle>

        
<!-- ***** Testimonials Ends ***** -->



<!-- jQuery -->
<script src="assets/js/jquery-2.1.0.min.js"></script>

<!-- Bootstrap -->
<script src="assets/js/popper.js"></script>
<script src="assets/js/bootstrap.min.js"></script>

<!-- Plugins -->
<script src="assets/js/scrollreveal.min.js"></script>
<script src="assets/js/waypoints.min.js"></script>
<script src="assets/js/jquery.counterup.min.js"></script>
<script src="assets/js/imgfix.min.js"></script> 
<script src="assets/js/mixitup.js"></script> 
<script src="assets/js/accordions.js"></script>

<!-- Global Init -->
<script src="assets/js/custom.js"></script>



</body>
</html>                            


website/templates/dashboard.html


{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Signed in succesfully!!</h4>
            <p> You can now enjoy our services to analyze your way  into fitness!
			</p>
              {% if session['username'] %}
            <p>
                You have logged in as {{session['username']}}

            </p>
              {% else %}
              <p> Not logged in yet</p>
              {% endif %}
            </p>
          </div>
        {% endfor %}
    {% endif %} 
{% endwith %}   


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Fit Fact</title>
<link href="https://fonts.googleapis.com/css?family=Raleway|Open+Sans" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
	body {
		background: #eeeeee;
		font-family: 'Open Sans', sans-serif;
	}
    .form-inline {
        display: inline-block;
    }
	.navbar {
		font-size: 14px;
		background: #fff;
		padding-left: 16px;
		padding-right: 16px;
		border-bottom: 1px solid #d6d6d6;
		box-shadow: 0 0 4px rgba(0,0,0,.1);		
	}
	.navbar .navbar-brand {
		color: #555;
		padding-left: 0;
		font-size: 20px;
		padding-right: 50px;
		font-family: 'Raleway', sans-serif;
		text-transform: uppercase;
	}
	.navbar .navbar-brand b {
		font-weight: bold;
		color: #f04f01;
	}
	.navbar ul.nav li {
		font-size: 96%;
		font-weight: bold;		
		text-transform: uppercase;
	}
	.navbar ul.nav li.active a, .navbar ul.nav li.active a:hover, .navbar ul.nav li.active a:focus {
		color: #f04f01 !important;
		background: transparent !important;
	}
	.search-box {
        position: relative;
    }
	.search-box input.form-control, .search-box .btn {
		font-size: 14px;
		border-radius: 2px !important;
	}
	.search-box .input-group-btn {
		padding-left: 4px;		
	}
	.search-box input.form-control:focus {
		border-color: #f04f01;
		box-shadow: 0 0 8px rgba(240,79,1,0.2);
	}
	.search-box .btn-primary, .search-box .btn-primary:active {
		font-weight: bold;
		background: #f04f01;
		border-color: #f04f01;
		text-transform: uppercase;
		min-width: 90px;
	}
	.search-box .btn-primary:focus {
		outline: none;
		background: #eb4e01;
		box-shadow: 0 0 8px rgba(240,79,1,0.2);
	}
	.search-box .btn span {
		transform: scale(0.9);
		display: inline-block;
	}
	.navbar ul li i {
		font-size: 18px;
	}
	.navbar .dropdown-menu i {
		font-size: 16px;
		min-width: 22px;
	}
	.navbar .dropdown.open > a {
		background: none !important;
	}
	.navbar .dropdown-menu {
		border-radius: 1px;
		border-color: #e5e5e5;
		box-shadow: 0 2px 8px rgba(0,0,0,.05);
	}
	.navbar .dropdown-menu li a {
		color: #777;
		padding: 8px 20px;
		line-height: normal;
		font-size: 14px;
	}
	.navbar .dropdown-menu li a:hover, .navbar .dropdown-menu li a:active {
		color: #333;
	}
	.navbar .navbar-form {
		border: none;
	}
	@media (min-width: 992px){
		.form-inline .input-group .form-control {
			width: 225px;			
		}
	}
	@media (max-width: 992px){
		.form-inline {
			display: block;
		}
	}
</style>
</head> 
<body>
<nav class="navbar navbar-default navbar-expand-lg navbar-light">
	<div class="navbar-header">
		<a class="navbar-brand" href="#">THE FIT FACT <b> USER DASHBOARD  </b></a>  		
		
		<form class="navbar-form form-inline navbar-right ml-auto">
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">

        <li><a href="/predict" id="home"> Predict Stress</a></li>
        <li><a href="/analyze" id="home"> Analyse Fitness</a></li>
        {% if session ['username'] %}
				<li><a href="/logout" id="home"> Log out</a></li>
        {% endif %} 	
				</span>
			</div>

		</form>		
	</div>
</nav>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

<title>The Fit Fact</title>

<!-- Additional CSS Files -->
<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="assets/css/font-awesome.css">

<link rel="stylesheet" href="assets/css/templatemo-training-studio.css">

</head>

<body>


<!-- ***** Main Banner Area Start ***** -->
			

   <video autoplay muted loop id="bg-video">
        <source src="{{url_for('static', filename='gym-video.mp4')}}"/>
    </video> 
	
   
<STYle>
/* Style the video: 100% width and height to cover the entire window */
#bg-video {
  z-index:1;
  width:100%;
}

.card {
  /* Add shadows to create the "card" effect */
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  position: absolute;
  z-index:2;
  background-color: rgba(250, 248, 242, 0.808);
  margin-left: 10%;
  margin-right: 40%;
  margin-top: 5%;
  margin-bottom: 60%;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
}

/* Add some content at the bottom of the video/page */
.content {
  position: fixed;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  color: #f1f1f1;
  width: 100%;
  padding: 20px;
}
#ex1{
  padding-left: 50px;
}
/* Style the button used to pause/play the video */
#myBtn {
  width: 200px;
  font-size: 18px;
  padding: 10px;
  border: none;
  background: #000;
  color: #fff;
  cursor: pointer;
}

#myBtn:hover {
  background: #ddd;
  color: black;
}

#titles{
  padding: 50px;
  z-index:1;
}
</STYle>

        
<!-- ***** Testimonials Ends ***** -->



<!-- jQuery -->
<script src="assets/js/jquery-2.1.0.min.js"></script>

<!-- Bootstrap -->
<script src="assets/js/popper.js"></script>
<script src="assets/js/bootstrap.min.js"></script>

<!-- Plugins -->
<script src="assets/js/scrollreveal.min.js"></script>
<script src="assets/js/waypoints.min.js"></script>
<script src="assets/js/jquery.counterup.min.js"></script>
<script src="assets/js/imgfix.min.js"></script> 
<script src="assets/js/mixitup.js"></script> 
<script src="assets/js/accordions.js"></script>

<!-- Global Init -->
<script src="assets/js/custom.js"></script>



</body>
</html>                            



website/templates/home.html
{% extends "base.html" %} {% block title %}Login{% endblock %} 
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Signed out succesfully!!</h4>
            <p> Hope you enjoyed our services!</p>
            <hr>
            <p class="mb-0">Analyze your way back into fitness soon!
            
            </p>
          </div>
        {% endfor %}
    {% endif %} 
{% endwith %}  
{% endblock %} 


website/templates/stress.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>The Fit Fact</title>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Hind:300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  
</head>

<!-- ***** Main Banner Area End ***** -->

<body style="background: #000;">
 <div class="login">
	<h1>Fitness Check!</h1>

     <!-- Main Input For Receiving Query to our ML -->
    <form action="{{ url_for('auth.predict')}}"method="post">
    	
        <input type="text" name="Step Count" placeholder="Step Count" required="required" />
		    <input type="text" name="Mood" placeholder="Mood" required="required" />
        <input type="text" name="Calories Burned" placeholder="Calories Burned" required="required" />
        <input type="text" name="Hours of Sleep" placeholder="Hours of Sleep" required="required" />
        <input type="text" name="Weight in kg" placeholder="Weight in kg" required="required" />
        <input type="text" name="Average Heart Rate" placeholder="Average Heart Rate" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Predict Stress Level</button>

    </form>

   <br>
   <br>
   
   {{ prediction_text }}
   <br>
   <a href="{{url_for('auth.exposition')}}" class="btn btn-primary btn-block btn-large">Get full report</a>


 </div>
</body>
</html>

website/templates/success1.html
<div class="">
    <form class="" action="/" method="POST">
    <input type="text" name="file" value="" placeholder="Enter the name of the file uploaded">
    <input type = "text" name="variable" value="" placeholder="Enter the metric to be visualised">
    <input type="submit" name="" value="submit"> 
    </form>
</div>